---
 - name: create inventory file
   shell: touch inventory
   register: create_inventory_file
 - name: write [all] to inventory file
   shell: echo [all] > inventory
   register: all_in_inventory
 - name: get_remote_machine_ips
   shell: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name = tag:Name,Values = play_server" --output text >> inventory
   register: machine_ips
 - name: print it out
   debug:
     msg: "{{ machine_ips.stdout_lines }}"